
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120


# 「and」「or」の使用を許可
AndOr:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - vendor/**/*
    - tmp/**/*